Updates for PureScript 0.11
purescript-contrib/purescript-ace pull request #25
Opened 2017-04-07 02:32 UTC by NasalMusician

I wanted to help update this package for PureScript 0.11. I updated the dependencies and changed IsForeign instances to read* functions. I have verified that this builds with the latest compiler.

Thanks!

2017-04-07 02:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slamdata/purescript-ace?pullRequest=25) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slamdata/purescript-ace?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slamdata/purescript-ace?pullRequest=25) it.</sub>

2017-04-11 19:25 UTC, natefaubion requested changes
Looks good! Just needs an updated `package.json` so Travis can run.

2017-04-11 19:26 UTC, natefaubion requested changes

2017-04-11 19:26 UTC, natefaubion commented on src/Ace/Types.purs
> +    >>= (map readString >>> sequence)
`map f >>> sequence` = `traverse`

2017-04-11 20:01 UTC, natefaubion commented
Looks like the examples/tests need to be updated.

2017-04-11 21:22 UTC, NasalMusician commented
Okay I believe it should be good now. As a bonus I got the Travis build working too ;) Thanks for the tips!

2017-04-11 21:43 UTC, natefaubion approved these changes

2017-04-11 21:43 UTC, merged

2017-04-11 21:44 UTC, natefaubion commented
Thanks!